Update latest.yml

diff --git a/.github/workflows/latest.yml b/.github/workflows/latest.yml
--- a/.github/workflows/latest.yml
+++ b/.github/workflows/latest.yml
@@ -1,27 +1,57 @@
-name: Security check - Bandit CSNA
+name: Bandit Scan
 
 on:
   push:
-    branches:
-      - master
+    branches: master
 
 jobs:
-  build:
+  bandit:
+    name: Bandit Scan
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
+      - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Python security check using Bandit CSNA and output as JSON
-        uses: kmcquade/bandit-report-artifacts-json@0.0.1
-        with:
-          python_version: 3.8.10
-          project_path: .
-          ignore_failure: false
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install bandit
+          pip install jq
 
-      - name: Security check report artifacts
+      - name: Run Bandit
+        id: bandit
+        run: |
+          bandit -r . -ll -f json -o bandit_report.json || echo "::set-output name=bandit_failed::true"
+          pwd
+
+      - name: Parse Bandit Report
+        id: parse_report
+        if: steps.bandit.outputs.bandit_failed != 'true'
+        run: |
+          cat bandit_report.json | jq -c '.' > bandit_report_formatted.json || echo "::set-output name=parse_failed::true"
+
+      - name: Upload artifact
         uses: actions/upload-artifact@v2
-        if: failure()
         with:
-          name: Security report
-          path: output/.
+          name: Bandit Report
+          path: bandit_report_formatted.json
+
+      - name: Show Bandit Report in Issue
+        if: steps.parse_report.outputs.parse_failed == 'true'
+        uses: actions/github-script@v4
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const report = require('./bandit_report_formatted.json');
+            const commentBody = `**Bandit Scan Results:**
+
+            ${JSON.stringify(report, null, 2)}
+
+            ![Bandit Report](./bandit_report_formatted.json)`;
+
+            github.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            })
