Update secret_scan.yml

diff --git a/.github/workflows/secret_scan.yml b/.github/workflows/secret_scan.yml
--- a/.github/workflows/secret_scan.yml
+++ b/.github/workflows/secret_scan.yml
@@ -1,53 +1,90 @@
-name: Secret Scan
+name: Detect Secrets
 
 on:
   push:
     branches:
       - master
-  workflow_dispatch:
+  pull_request:
+    branches:
+      - master
 
 jobs:
-  security_scan:
-    name: Security Scan
+  ubuntu:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Set Python 3 as default
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3
 
-      - name: Install TruffleHog and Dependencies
+      - name: Install detect-secrets using pip
         run: |
-          sudo apt-get install -y python3 python3-pip
-          pip install trufflehog
+          python -m pip install detect-secrets
 
-      - name: Verify TruffleHog Installation
-        run: trufflehog --version
-
-      - name: Debug Information
+      - name: Run detect-secrets tool
         run: |
-          echo "Current Working Directory:"
-          pwd
+          detect-secrets --version
+          detect-secrets scan --all-files --force-use-all-plugins --exclude-files FETCH_HEAD > ${{ github.workspace }}/detect-secrets.json
 
-          echo "Contents of Repository Directory:"
-          ls -al
-
-          echo "Contents of Target Directory:"
-          ls -al ${{ github.workspace }}
-
-      - name: Run TruffleHog Scan
-        run: |
-          bash -c "trufflehog --entropy=True --json ${{ github.workspace }} > trufflehog_report.json"
-
-      - name: Display TruffleHog Secrets
-        run: |
-          if [ -s trufflehog_report.json ]; then
-            echo "TruffleHog Secrets found:"
-            cat trufflehog_report.json
-          else
-            echo "No TruffleHog secrets found."
-          fi
-
-      - name: Upload TruffleHog Report
+      - name: Publish results in the Pipeline Artifact
         uses: actions/upload-artifact@v2
         with:
-          name: trufflehog-report
-          path: trufflehog_report.json
+          name: detect-secrets-ubuntu
+          path: ${{ github.workspace }}/detect-secrets.json
+
+      - name: Analyzing detect-secrets results
+        run: |
+          dsjson=$(cat ${{ github.workspace }}/detect-secrets.json)
+          echo "${dsjson}"
+
+          count=$(echo "${dsjson}" | jq -c -r '.results | length')
+
+          if [ $count -gt 0 ]; then
+            msg="Secrets were detected in code. ${count} file(s) affected."
+            echo "##[error]${msg}"
+            echo "##[task]${msg}."
+            exit 1
+          else
+            echo "No secrets detected."
+          fi
+
+  windows:
+    runs-on: windows-latest
+    steps:
+      - name: Set Python 3 as default
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3
+
+      - name: Install detect-secrets using pip
+        run: |
+          python -m pip install detect-secrets==1.0.3
+
+      - name: Run detect-secrets tool
+        run: |
+          detect-secrets --version
+          detect-secrets scan --all-files --force-use-all-plugins > ${{ github.workspace }}/detect-secrets.json
+
+      - name: Publish results in the Pipeline Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: detect-secrets-windows
+          path: ${{ github.workspace }}/detect-secrets.json
+
+      - name: Analyzing detect-secrets results
+        run: |
+          $dsjson = Get-Content ${{ github.workspace }}/detect-secrets.json
+          Write-Output $dsjson
+
+          $dsObj = $dsjson | ConvertFrom-Json
+          $count = ($dsObj.results | Get-Member -MemberType NoteProperty).Count
+
+          if ($count -gt 0) {
+            $msg = "Secrets were detected in code. $count file(s) affected."
+            Write-Error $msg
+            Write-Host "##[error]$msg"
+            exit 1
+          }
+          else {
+            Write-Host "No secrets detected."
+          }
